config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/news', to: 'news#index'
  get '/portfolio', to: 'portfolios#index', as: 'portfolio'
  get '/prices', to: 'pages#prices', as: 'prices'
  resources :portfolios, only: [ :new, :create, :destroy ] do
    resources :ownedcurrencies, only: [:create]
  end
  resources :subscriptions, only: [:create, :destroy ]
  resources :users, only: [:show] do
    member do
      get     '/posts',         to: 'users#posts'

      post '/follow', to: 'users#follow', as: :user_follow
      post '/unfollow', to: 'users#unfollow', as: :user_unfollow

      post    '/favorites',     to: 'users#favorites'
      get     '/favorites',     to: 'users#favorites'
      delete  '/favorites',     to: 'users#remove_favorites'
    end
  end
  resources :posts do
    member do
      put '/upvote', to: 'posts#upvote'
      put '/downvote', to: 'posts#downvote'
    end
    resources :comments, only: [:create]
  end
  resources :comments, only: [:destroy]

  resources :ownedcurrencies, only: [ :index, :show, :new, :destroy ]

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.present? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :content, length: { maximum: 500 }
  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.post = @post
    @comment.user = current_user
    authorize @comment
    if @comment.save
      respond_to do |format|
        format.html { redirect_to post_path(@post) }
        format.js
      end
    else
      respond_to do |format|
        format.html { render 'posts/show' }
        format.js
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    authorize @comment
    @comment.destroy
    redirect_to user_path(@comment.user)
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/views/comments/_form.html.erb
<%= simple_form_for([post, comment], remote: true) do |f| %>
  <%= f.input :content, label: false %>
  <%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %>

app/views/comments/_individual.html.erb
<div class="comment-card" id="comments-card">
  <div class="card-meta"><time style="color: gray; font-size: 12px;"><%= comment.created_at.strftime("%b %e, %Y - %l:%M %p") %></time></div>
  <article class="card-content">
    <p><%= comment.content %></p>
  </article>
  <div class="post-and-comment-card-user">
    <span>
      <%= link_to user_path(comment.user), class: 'post-and-comment-card-user-color' do %>
      <span><%= comment.user.username %></span>
      <% end %>
  <% if policy(comment).destroy? %>
    <%= link_to comment_path(comment), method: :delete, data: { confirm: "Delete Post?" } do %>
      <i class="fas fa-trash trash-icon"></i>
    <% end %>
  <% end %></span>
  </div>
</div>

app/views/comments/_show.html.erb
<% post.comments.order("created_at DESC").each do |comment| %>
  <%= render 'comments/individual', comment: comment %>
<% end %>

app/views/comments/create.js.erb
function refreshForm(innerHTML) {
  const newCommentForm = document.getElementById('new_comment');
  newCommentForm.innerHTML = innerHTML;
}

function addComment(reviewHTML) {
  const comments = document.getElementById('comments');
  comments.insertAdjacentHTML('afterbegin', reviewHTML);
}

<% if @comment.errors.any? %>
  refreshForm('<%= j render "comments/form", post: @post, comment: @comment %>');
<% else %>
  addComment('<%= j render "comments/individual", comment: @comment %>');
  refreshForm('<%= j render "comments/form", post: @post, comment: Comment.new %>');
<% end %>