config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/news', to: 'news#index'
  get '/portfolio', to: 'portfolios#index', as: 'portfolio'
  get '/prices', to: 'pages#prices', as: 'prices'
  resources :portfolios, only: [ :new, :create, :destroy ] do
    resources :ownedcurrencies, only: [:create]
  end
  resources :subscriptions, only: [:create, :destroy ]
  resources :users, only: [:show] do
    member do
      get     '/posts',         to: 'users#posts'

      post '/follow', to: 'users#follow', as: :user_follow
      post '/unfollow', to: 'users#unfollow', as: :user_unfollow

      post    '/favorites',     to: 'users#favorites'
      get     '/favorites',     to: 'users#favorites'
      delete  '/favorites',     to: 'users#remove_favorites'
    end
  end
  resources :posts do
    member do
      put '/upvote', to: 'posts#upvote'
      put '/downvote', to: 'posts#downvote'
    end
    resources :comments, only: [:create]
  end
  resources :comments, only: [:destroy]

  resources :ownedcurrencies, only: [ :index, :show, :new, :destroy ]

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.present? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div>
    <i>Stay ahead of the curve in the world of Cryptocurrency</i>
  </div>
  <div>
    © CoinSpread 2018
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-fixed-top">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <!-- <div class="coin-img">
       #image_tag ("logo.png"), class: "navbar-logo"
    </div> -->
  <% end %>
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <div class="navbar-name">
      <h4 style="font-size: 32px;"><strong><i>CoinSpread</i></strong></h4>
    </div>
  <% end %>
  <div class="navbar-prices">
    <div class="bitcoin-container">
      <h2>Bitcoin
        <p style="color: #5186DF"><span id="bitcoin-price"></span></p>
      </h2>
    </div>
    <div class="global-container">
      <h2>Global Marketcap
        <p style="color: #5186DF"><span id="marketcap"></span></p>
      </h2>
    </div>
  </div>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if user_signed_in? %>
      <!-- Links when logged in -->
      <%= link_to "My Portfolio", portfolio_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if current_user.photo %>
            <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li>
                <%= link_to user_path(current_user.id) do %>
                  <i class="fa fa-user"></i>  <%= "Profile" %>
                <% end %>
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>
  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>