config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/news', to: 'news#index'
  get '/portfolio', to: 'portfolios#index', as: 'portfolio'
  get '/prices', to: 'pages#prices', as: 'prices'
  resources :portfolios, only: [ :new, :create, :destroy ] do
    resources :ownedcurrencies, only: [:create]
  end
  resources :subscriptions, only: [:create, :destroy ]
  resources :users, only: [:show] do
    member do
      get     '/posts',         to: 'users#posts'

      post '/follow', to: 'users#follow', as: :user_follow
      post '/unfollow', to: 'users#unfollow', as: :user_unfollow

      post    '/favorites',     to: 'users#favorites'
      get     '/favorites',     to: 'users#favorites'
      delete  '/favorites',     to: 'users#remove_favorites'
    end
  end
  resources :posts do
    member do
      put '/upvote', to: 'posts#upvote'
      put '/downvote', to: 'posts#downvote'
    end
    resources :comments, only: [:create]
  end
  resources :comments, only: [:destroy]

  resources :ownedcurrencies, only: [ :index, :show, :new, :destroy ]

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.present? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :cryptocurrency
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def create
    @subscription = Subscription.new(subscription_params)
    @subscription.user = current_user
    authorize @subscription
    if @subscription.save
      redirect_to root_path
    else
      flash[:alert] = "Subscription could not be created"
      redirect_to root_path
    end
  end

  def destroy
    @subscription = Subscription.find(params[:id])
    authorize @subscription
    @subscription.destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def subscription_params
    params.require(:subscription).permit(:cryptocurrency_id)
  end
end

app/views/subscriptions/_form.html.erb
<div class="search-box-bottom-box">

    <div class="form-for-subscription">
    <%= simple_form_for @subscription do |f| %>
      <%= f.association :cryptocurrency, collection:Cryptocurrency.all.order(:name) , label: false , input_html: {class: "select2"} %>
    </div>
    <div class="add-coin-button">
    <%= f.submit "Add Coin", :class => "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/subscriptions/_table.html.erb
<div class="table100 ver5 m-b-110">
  <div class="table100-head">
    <table>
      <thead>
        <tr class="row100 head">
          <th class="cell100 column1"><strong>#</strong></th>
          <th class="cell100 column2"><strong>Name</strong></th>
          <th class="cell100 column3"><strong>Market Cap</strong></th>
          <th class="cell100 column4"><strong>Price</strong></th>
          <th class="cell100 column5"><strong>Volume</strong></th>
          <th class="cell100 column6"><strong>Circulating Supply</strong></th>
          <th class="cell100 column7"><strong>Change (24h)</strong></th>
          <th class="cell100 column8"></th>
        </tr>
      </thead>
    </table>
  </div>

  <div class="table100-body js-pscroll ps ps--active-y">
    <table>
      <tbody>
        <% if current_user %>
          <% current_user.subscriptions.each do |subscription| %>
            <tr class="row100 body">
              <td class="cell100 column1"><%=subscription.cryptocurrency.rank%> </td>
              <td class="cell100 column2"><strong><%=subscription.cryptocurrency.name%></strong></td>
              <td class="cell100 column3">$<%=subscription.cryptocurrency.Marketcap%></td>
              <td class="cell100 column4">$<%=subscription.cryptocurrency.market_price %></td>
              <td class="cell100 column5">$<%=subscription.cryptocurrency.Volume %></td>
              <td class="cell100 column6"><%=subscription.cryptocurrency.Supply%></td>
              <td class="cell100 column7"><%=subscription.cryptocurrency.Change%>%</td>
              <td class="cell100 column8">
                <%= link_to subscription_path(subscription), method: :delete do %>
                  <i class="far fa-times-circle table-row-delete"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>