config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/news', to: 'news#index'
  get '/portfolio', to: 'portfolios#index', as: 'portfolio'
  get '/prices', to: 'pages#prices', as: 'prices'
  resources :portfolios, only: [ :new, :create, :destroy ] do
    resources :ownedcurrencies, only: [:create]
  end
  resources :subscriptions, only: [:create, :destroy ]
  resources :users, only: [:show] do
    member do
      get     '/posts',         to: 'users#posts'

      post '/follow', to: 'users#follow', as: :user_follow
      post '/unfollow', to: 'users#unfollow', as: :user_unfollow

      post    '/favorites',     to: 'users#favorites'
      get     '/favorites',     to: 'users#favorites'
      delete  '/favorites',     to: 'users#remove_favorites'
    end
  end
  resources :posts do
    member do
      put '/upvote', to: 'posts#upvote'
      put '/downvote', to: 'posts#downvote'
    end
    resources :comments, only: [:create]
  end
  resources :comments, only: [:destroy]

  resources :ownedcurrencies, only: [ :index, :show, :new, :destroy ]

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.present? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  has_many :comments, dependent: :destroy
  belongs_to :user
  validates :content, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :destroy, :upvote, :downvote]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @posts = policy_scope(Post).order("created_at DESC")
  end

  def new
    @post = Post.new
    authorize @post
    @comment = Comment.new(post_id: params[:post_id])
  end

  def show
    @comment = Comment.new
    @comments = @post.comments
    respond_to do |format|
      format.js
      # format.html { render :new }
    end
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    authorize @post
    if @post.save
      @posts = policy_scope(Post).order("created_at DESC").take(10)
      @comment = Comment.new
      respond_to do |format|
        format.js
        # format.html { redirect_to root_path }
      end
    else
      respond_to do |format|
        format.js
        # format.html { render :new }
      end
    end
  end

  def destroy
    @post.destroy
    redirect_to user_path(@post.user)
  end

  def upvote
    authorize @post
    @post.upvote_by current_user
    respond_to :js
  end

  def downvote
    authorize @post
    @post.downvote_from current_user
    respond_to :js
  end

  private

  def set_post
    @post = Post.find(params[:id])
    authorize @post
  end

  def post_params
    params.require(:post).permit(:content)
  end
end

app/views/posts/_following_index.html.erb
<% @posts.order("created_at DESC").each do |post| %>
  <% if current_user && current_user.following_users.include?(post.user) %>
    <%= render 'posts/individual', post: post %>
  <% end %>
<% end %>

app/views/posts/_form.html.erb
<%= simple_form_for(post, remote: true) do |f| %>
  <div class="post-title-form"> <%= f.input :content, label: false %></div>
  <div class="post-form-submit">
    <%= f.submit 'Submit', class: 'btn btn-primary btn-submit-post' %>
  </div>
<% end %>
<button type="button" style="display: none", class="btn btn-back-dashboard" id="back_to_dashboard">Back to dashboard</button>

app/views/posts/_hot_index.html.erb
<% @posts.order("cached_weighted_score DESC").take(10).each do |post| %>
  <%= render 'posts/individual', post: post %>
<% end %>

app/views/posts/_index.html.erb
<% @posts.order("created_at DESC").take(10).each do |post| %>
  <%= render 'posts/individual', post: post %>
<% end %>

app/views/posts/_individual.html.erb
<div class="home-post-show-first">
  <article class="home-post-show-second">
    <div class="home-post-show-third">
      <div class="vote-card">
        <div class="post-indiv-avatar">
          <%= cl_image_tag(post.user.photo, :transformation=>[
          {:effect=>"cartoonify"},
          {:height=>35, :width => 35, :crop=>"fill"}
          ]) %>
        </div>
        <div class="voteButtons-<%= post.id %> vote-buttons-container">
          <%= render 'posts/vote_buttons', post: post %>
        </div>
      </div>
      <div class="home-post-card">
        <div class="post-card-header">
          <span class="user-profile-link-container">
            <%= link_to user_path(post.user), class: 'user-profile-link' do %>
              <span><%= post.user.username %></span>
            <% end %>
          </span>
          <span class="post-created-at"><%= post.created_at.strftime("%b %e, %Y - %l:%M %p") %></span>
        </div>
        <div class="post-card-content">
          <span><%= post.content %></span>
        </div>
        <div class="post-card-footer">
          <ul class="post-card-footer-list">
            <li><%= link_to "Comment", post_path(post), class: 'view-comments-link', "data-id": post.id, remote: true %> <span class="post-comment-count"><%= post.comments.count %></span> </li>
          </ul>
        </div>
        <div class="home_post_comment"><%= render 'comments/form', post: post, comment: @comment %></div>
      </div>
    </div>
  </article>
</div>

app/views/posts/_show.html.erb
<div class="posts-show-wrapper">
  <div class="post-inner-wrapper">
    <div class="prices-back-right">
      <%= link_to prices_path, remote: true do %>
        <span>Dashboard <i class="fas fa-angle-double-right"></i></span>
      <% end %>
    </div>
    <div class="post-show">
      <div class="vote-card">
        <% if policy(post).upvote? %>
          <%= link_to upvote_post_path(post), method: :put do %>
            <span class="glyphicon glyphicon-chevron-up upvote-icon"></span>
          <% end %>
        <% end %>
        <div class="vote-weighted"><%= post.weighted_score %></div>
        <% if policy(post).downvote? %>
          <%= link_to downvote_post_path(post), method: :put do %>
            <span class="glyphicon glyphicon-chevron-down downvote-icon"></span>
          <% end %>
        <% end %>
      </div>
      <div class="profile-foto">
        <%= cl_image_tag(post.user.photo, :transformation=>[
            {:effect=>"cartoonify"},
            {:effect=>"outline:100", :color=>"white"},
            {:background=>"white"},
            {:height=>100, :crop=>"scale"}
         ]) %>
      </div>
      <div class="post-show-card-top">
        <div class="card-meta"><time style="color: gray; font-size: 12px;"><%= post.created_at.strftime("%b %e, %Y - %l:%M %p") %></time></div>
        <article class="card-content">
          <p style="font-size:24px;"><%= post.content %></p>
        </article>
        <div class="post-and-comment-card-user">
          <span>
            <%= link_to user_path(post.user), class: 'post-and-comment-card-user-color' do %>
            <%= post.user.username %>
            <% end %>
            </span>
        </div>
        <% if policy(post).destroy? %>
          <%= link_to post_path, method: :delete, data: { confirm: "Delete Post?" } do %>
            <i class="fas fa-trash trash-icon"></i>
          <% end %>
        <% end %>
      </div>
    </div>
    <% unless !current_user %>
      <div class="comments">
        <h5>Add your comment:</h5>
        <div id="new_comment"><%= render 'comments/form', post: post, comment: comment %></div>
      <% end %>
      <div id="comments">
        <%= render 'comments/show', post: post %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_vote_buttons.html.erb
<% if current_user %>
  <%= link_to upvote_post_path(post), class: 'upvote-icon-link', method: :put, remote: true do %>
    <span class="glyphicon glyphicon-chevron-up upvote-icon"></span>
  <% end %>
<% else %>
  <%= link_to new_user_session_path, class: 'upvote-icon-link', method: :get do %>
    <span class="glyphicon glyphicon-chevron-up upvote-icon"></span>
  <% end %>
<% end %>
<div class="vote-weighted"><%= post.weighted_score %></div>
<% if current_user %>
  <%= link_to downvote_post_path(post), class: 'downvote-icon-link', method: :put, remote: true do %>
    <span class="glyphicon glyphicon-chevron-down downvote-icon"></span>
  <% end %>
<% else %>
  <%= link_to new_user_session_path, class: 'downvote-icon-link', method: :get do %>
    <span class="glyphicon glyphicon-chevron-down downvote-icon"></span>
  <% end %>
<% end %>

app/views/posts/create.js.erb
function refreshForm(innerHTML) {
  const newCommentForm = document.getElementById('new_post');
  newCommentForm.innerHTML = innerHTML;
}

function addPost(reviewHTML) {
  const posts = document.getElementById('posts');
  posts.insertAdjacentHTML('afterbegin', reviewHTML);
}
console.log("im inside create js");
<% if @post.errors.any? %>
  refreshForm('<%= j render "posts/form", post: @post %>');
<% else %>
  addPost('<%= j render "posts/individual", post: @post %>');
  refreshForm('<%= j render "posts/form", post: Post.new %>');
<% end %>

app/views/posts/downvote.js.erb
function refreshVoteButtons(innerHTML, id) {
  const voteButtons = document.querySelectorAll('.voteButtons-' + id);
  voteButtons.forEach((voteButton) => {
    voteButton.innerHTML = innerHTML;
  });
}
refreshVoteButtons('<%= j render "vote_buttons", post: @post %>', '<%= @post.id %>');

app/views/posts/index.html.erb
<h1 class="text-center">All Posts</h1>
<div class="container">
  <% @posts.each do |post| %>
    <div class="card">
      <div class="card-meta"><time><%= post.created_at.strftime("%b %e, %Y - %l:%M %p") %></time>
        <% unless current_user != post.user %>
          <%= link_to post_path(post), method: :delete, data: { confirm: "Delete Post?" } do %>
              <i class="fas fa-trash trash-icon"></i>
          <% end %>
        <% end %>
      </div>
      <article class="card-content"><p><%= post.content %></p></article>
      <div class="card-user"> By <span class="card-username"><%= post.user.email %></span> <%= link_to "Comments", post_path(post) %> </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="wrapper-for-post-page">
<%= render 'form', post: @post %>
</div>

app/views/posts/show.html.erb
<%= render "show", post: @post, comment: @comment %>

app/views/posts/show.js.erb
// var viewLinks = document.querySelectorAll(".open-post-button");
// viewLinks.forEach((button) => {
// console.log("start JS");
//   button.addEventListener("click", (event) => {
//     console.log(event.currentTarget);
//     var postsContainer = document.querySelector('.post-partial-container');
//     postsContainer.innerHTML = `<%= j render 'posts/show', post: @post, comment: @comment %>`;
//   })
// })

// var postsContainer = document.querySelector('.post-partial-container');
var prices = document.querySelector(".prices-inner-container");
prices.setAttribute("style", "display: none;");

var temporaryContainer = document.querySelector("#temporary-container");
// var back = document.querySelector("#back_to_dashboard");
// var news = document.querySelector(".all-news-container");

// back.style.display = "block";
// if (prices.style.display === "none") {
//   news.style.display = "none";
// }
// else {
//   prices.style.display = "none";
// }

// postsContainer.style.display = "block"
temporaryContainer.innerHTML = '<%= j render 'posts/show', post: @post, comment: @comment %>';

app/views/posts/upvote.js.erb
function refreshVoteButtons(innerHTML, id) {
  const voteButtons = document.querySelectorAll('.voteButtons-' + id);
  voteButtons.forEach((voteButton) => {
    voteButton.innerHTML = innerHTML;
  });
}
refreshVoteButtons('<%= j render "vote_buttons", post: @post %>', '<%= @post.id %>');